### ISSUE TITLE
Glayout TODO tasks

### ISSUE THREAD

**Issue by alibillalhammoud** [idea-fasoc/OpenFASOC#310]
- [ ] Include a More Extensive Header for Glayout Compiled Files
- [ ] Review and enhance the content in the markdown files located in the rag_data folder.
- [ ] Ensure all convo-related files are located in the components folder within the flow directory.
- [ ] Include comprehensive comments throughout compiled code.

**Comment by alibillalhammoud** [comment]
@chetanyagoyal @srpathen @arldai

**Comment by chetanyagoyal** [comment]
Task 1 is being handled by #321
